### ISSUE TITLE
[1.18.2] Crashes clicking on mod in Forge menu

### ISSUE THREAD

**Issue by FIM43-Redeye** [Cristelknight999/Cristel-Lib#18]
Version 1.0.0.
https://mclo.gs/misboWJ
To reproduce:
-Open CABIN: Create Above & Beyond in Newer, or probably any install with Cristel Lib's Forge version.
-Go to the mods menu.
-Click Cristel Lib.
-Crash.

**Comment by 3944Realms** [comment]
["CC BY-NC-ND 4.0"](https://github.com/Cristelknight999/Cristel-Lib/blob/a58077b58cfa253a9fce7b9ca73893b737e2c15b/forge/src/main/resources/META-INF/mods.toml#L14C1-L14C49)
in fact ：Description: mouseClicked event handler

java.lang.IllegalArgumentException: Root resources can only be filenames, not paths (no / allowed!)
	at net.minecraft.server.packs.AbstractPackResources.m_5542_(AbstractPackResources.java:47) ~[client-1.18.2-20220404.173914-srg.jar%23171!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraftforge.client.gui.ModListScreen.lambda$updateCache$12(ModListScreen.java:414) ~[forge-1.18.2-40.2.21-universal.jar%23176!/:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
