### ISSUE TITLE
[1.20.1] 1.1.2 Crashes on Quilt

### ISSUE THREAD

**Issue by Aninuscsalas** [Cristelknight999/Cristel-Lib#2]
https://mclo.gs/zsF1lLY

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!
Time: 2023-07-17 13:29:12
Description: Initializing game
java.lang.NoSuchMethodError: 'org.quiltmc.qsl.resource.loader.api.ResourcePackActivationType net.minecraft.class_3262.getActivationType()'
	at net.minecraft.class_3288.handler$zco000$quilt_resource_loader$quilt$onInit(class_3288.java:545)
	at net.minecraft.class_3288.<init>(class_3288.java:66)
	at net.minecraft.class_3288.method_14456(class_3288.java:52)
	at net.minecraft.class_3288.method_45275(class_3288.java:48)
	at net.minecraft.class_1065.method_45257(class_1065.java:88)
	at net.minecraft.class_7678.method_14453(class_7678.java:39)
	at net.minecraft.class_3283.method_29212(class_3283.java:39)
	at net.minecraft.class_3283.method_14445(class_3283.java:32)
	at net.minecraft.class_310.<init>(class_310.java:513)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_3288.handler$zco000$quilt_resource_loader$quilt$onInit(class_3288.java:545)
	at net.minecraft.class_3288.<init>(class_3288.java:66)
	at net.minecraft.class_3288.method_14456(class_3288.java:52)
	at net.minecraft.class_3288.method_45275(class_3288.java:48)
	at net.minecraft.class_1065.method_45257(class_1065.java:88)
	at net.minecraft.class_7678.method_14453(class_7678.java:39)
	at net.minecraft.class_3283.method_29212(class_3283.java:39)
	at net.minecraft.class_3283.method_14445(class_3283.java:32)
	at net.minecraft.class_310.<init>(class_310.java:513)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by jsaggers** [comment]
I'm also getting the same crash.
Cristellib-1.1.2-quilt (I also tried the fabric version)
Trying to get towns and towers 1.11 working
Yes I have Quilted fabric api installed, version qfapi-7.0.6_qsl-6.0.4_fapi-0.85.0_mc-1.20.1
Any more information required just ask.

**Comment by Jamalam360** [comment]
Also experiencing this. looking into it

**Comment by bghyt** [comment]
+1 with the exact same issue here.

**Comment by Boba194230** [comment]
+1 same thing

**Comment by bipsydev** [comment]
+1 same, here's my stack trace with MixinTrace:
```
Mod Table Version: 2
Plugin Types: {quilted_fabric_loader=[Fabric], quilt_loader=[Quilt, Builtin]}
[16:35:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/lilit/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Quilt Env=CLIENT
[16:35:38] [main/INFO]: Compatibility level set to JAVA_17
[16:35:38] [main/ERROR]: Mixin prepare for mod quilt_resource_loader failed preparing ResourcePackMixin in #quilt_resource_loader:quilt_resource_loader.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: #quilt_resource_loader:quilt_resource_loader.mixins.json:ResourcePackMixin from mod quilt_resource_loader target net.minecraft.class_3262 was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: #quilt_resource_loader:quilt_resource_loader.mixins.json:ResourcePackMixin from mod quilt_resource_loader target net.minecraft.class_3262 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:243) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:167) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[16:35:38] [main/WARN]: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#quilt_resource_loader:quilt_resource_loader.mixins.json:ResourcePackMixin from mod quilt_resource_loader] from phase [DEFAULT] in config [#quilt_resource_loader:quilt_resource_loader.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:243) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:167) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) ~[quilt-loader-0.19.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: #quilt_resource_loader:quilt_resource_loader.mixins.json:ResourcePackMixin from mod quilt_resource_loader target net.minecraft.class_3262 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 14 more
Exception caught from launcher
java.lang.RuntimeException: Mixin transformation of org.quiltmc.loader.impl.launch.knot.UnusedEmptyTargetClass failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:458)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadIntoTarget(KnotClassLoader.java:243)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:167)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#quilt_resource_loader:quilt_resource_loader.mixins.json:ResourcePackMixin from mod quilt_resource_loader] from phase [DEFAULT] in config [#quilt_resource_loader:quilt_resource_loader.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: #quilt_resource_loader:quilt_resource_loader.mixins.json:ResourcePackMixin from mod quilt_resource_loader target net.minecraft.class_3262 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 14 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by ABaffledPenguin** [comment]
Experiencing this aswell.

**Comment by Cristelknight999** [comment]
Quilt works *sometimes* in the ide and *sometimes* it crashes because a mixin loading error. And the build version always crashes because of this error: 
```
java.lang.NoSuchMethodError: 'org.quiltmc.qsl.resource.loader.api.ResourcePackActivationType net.minecraft.class_3262.getActivationType()'
	at net.minecraft.class_3288.handler$zfp000$quilt_resource_loader$quilt$onInit(class_3288.java:545)
	at net.minecraft.class_3288.<init>(class_3288.java:66)
	at net.minecraft.class_3288.method_14456(class_3288.java:52)
	at net.minecraft.class_3288.method_45275(class_3288.java:48)
	at net.minecraft.class_1065.method_45257(class_1065.java:88)
	at net.minecraft.class_7678.method_14453(class_7678.java:39)
	at net.minecraft.class_3283.method_29212(class_3283.java:39)
	at net.minecraft.class_3283.method_14445(class_3283.java:32)
	at net.minecraft.class_310.<init>(class_310.java:513)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
If somebody can help me with this issue or could just fix it, that would be great.

Also build in common doesn't work now,.idk why. Simply use the build under the respective modloader

**Comment by PaperTarsier692** [comment]
+1 same

**Comment by Cristelknight999** [comment]
Please stop commenting useless stuff

**Comment by Feliks-WR** [comment]
YEP
Why can't we run Terralith, or towns and towers now??!?
Perhaps try and contact the Quilt dev team?
[crash-2023-10-01_14.02.00.2426-quilt_loader.txt](https://github.com/Cristelknight999/Cristel-Lib/files/12776757/crash-2023-10-01_14.02.00.2426-quilt_loader.txt)

**Comment by OroArmor** [comment]
I think this is due to the ExpectPlatform and maybe also the `Util` classes. I would fix this with two things:
1. Move the `Util#isTerrablenderLoaded` to the `TerrablenderUtil` class.
2. Split up the `CristelLibExpectPlatform` into one that handles Loader features, and on that handles Minecraft features. What I believe is happening is that the calls in the Mixin Plugin are then loading the `CristelLibExpectPlatform` which in turn loads some of the Minecraft Classes, which then cause the mixin to fail to apply since it was loaded with the default class loader and not Knot/FML (the one that applies the mixins)

This should probably fix the issue with Quilt!

**Comment by Cristelknight999** [comment]
Thanks! Finally someone who has some suggestions for a solution

**Comment by SettingDust** [comment]
@Cristelknight999 Quilt no 1.20.2 for now. The build works fine with 1.20.1. But can't test in development since the branch is in mc 1.20.2

**Comment by Cristelknight999** [comment]
why is there no quilt for 1.20.2 yet?

**Comment by SettingDust** [comment]
@Cristelknight999 How about a release for lower version such as 1.20.1

**Comment by Cristelknight999** [comment]
sorry. i had to play games and do school stuff. i‘ll upload it today i hope
